server.port=8901
spring.application.name=networkdisk-user-provider

# Dubbo Application
## The default value of dubbo.application.name is ${spring.application.name}
 dubbo.application.name=${spring.application.name}
# Dubbo Protocol
dubbo.protocol.name=dubbo
dubbo.protocol.port=20880
## Dubbo Registry
dubbo.registry.address=zookeeper://localhost:2181